apiVersion: apps/v1

kind: Deployment

metadata:
  name: springboot-deployment
  namespace: dev
  labels:
    app: springboot-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-pod

  template:
    metadata:
      name: springboot-pod
      labels:
        app: springboot-pod

    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: springboot-pod
      containers:
        - name: springboot-container
          image: springbootbackend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: springboot-backend-secret-config
            - configMapRef:
                name: springboot-backend-config          
