options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: order-api
  _SERVICE_NAME: order-api

steps:
  # Step 1: Build Docker image from Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - .

  # Step 2: Push Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA

  # Step 3: Deploy image to Cloud Run in us-east4 with VPC connector
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploying to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - --region=us-east4
      - --platform=managed
      - --allow-unauthenticated
      - --vpc-connector=postgres-sql-connector
      - --vpc-egress=all-traffic

images:
  - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA

timeout: "2000s"
