options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image from Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - .

  # Step 2: Push Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA

  # Step 3: Deploy image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - --region=us-east4
      - --platform=managed
      - --allow-unauthenticated

images:
  - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA

timeout: "2000s"
